### ISSUE TITLE
Java version?

### ISSUE THREAD

**Issue by ianp** [jidesoft/jide-oss#4]
If I try to compile with JDK 1.6 I run into the following error

```
[ERROR] /Users/ianp/Projects/jide-oss/src/com/jidesoft/popup/JidePopup.java:[1475,27] cannot find symbol
symbol  : method setAutoRequestFocus(boolean)
location: class com.jidesoft.swing.ResizableWindow
```

This is because the method is `@since 1.7`.

If I update the pom and try to compile with JDK 1.7 I get the following error:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project jide-oss: Compilation failure: Compilation failure:
[ERROR] /Users/ianp/Projects/jide-oss/src/com/jidesoft/plaf/windows/XPStyle.java:[639,29] error: cannot find symbol
```

Tis is because the class `sun.awt.image.CachingSurfaceManager` does not exist in JDK 1.7.

So, which version of Java are you guys using to build with?

Mac OS X 10.8.4.
